#!/bin/bash

script_dir=$(dirname "$0")
source "$script_dir/AutoSkyMulti.ini"

# Initialize all parameters

function AutoSkyMulti_init {
	# Parameter Initialization for AUTOSKYMULTI

	if [ ! -d "/$TMPDIR" ]; then
		mkdir "/$TMPDIR"
	fi
	if [ ! -d "/$TMPDIR/WXA" ]; then
		mkdir "/$TMPDIR/WXA"
	fi

	TFILET="$TMPDIR/alert.txtt" # temp file
	NFILE1="$TMPDIR/alert.txt1" # from NWS
	NFILE2="$TMPDIR/alert.txt2" # Just alert text
	NFILE3="$TMPDIR/alert.txt3" # Formulated alert message to play
	#
	ENABLEFILE="$TMPDIR/alert.enbl" # if exists then enable Auto SkyWarn
	FILESAVE="$TMPDIR/alert.save"   # we compare against this file to determine chan
	WFILE="$TMPDIR/alert.work"
	WFILEWC="$TMPDIR/alert.workwc"
	if [ -z $AutoSkyMulti_log ]; then
		AutoSkyMulti_log="$TMPDIR/AutoSkyMulti-log.txt"
	fi
	#
	WXT="$TMPDIR/WXA"     # where you store the weather tail message
	TAILMSG="wx-tail.wav" # point to this file in rpt.conf
	WXA="$BASEDIR/SOUNDS" # where the sounds are
	TFILEW="alert.wav"    # temp file

	#Xresult=98
	#Yresult=99
	#
	A1FILE=asn96
	A2FILE=asn97
	A3FILE=asn98
	#
	ANNN="xx"  # Announcement Number
	FOUNDONE=0 # Found at least one match
	#
	CATWAV=$(which sox)
	BUILD1="asn"
	BUILD3=".wav"

}

# LIST OF COUNTIES TO PULL ALERTS FOR
declare -g -a OF
OF[1]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC045&y=0" # Faulkner
OF[2]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC051&y=0" # Garland
OF[3]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC053&y=0" # Grant
OF[4]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC085&y=0" # Lonoke
OF[5]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC105&y=0" # Perry
OF[6]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC119&y=0" # Pulaski
OF[7]="https://alerts.weather.gov/cap/wwaatmget.php?x=ARC125&y=0" # Saline

# LIST OF ALERTS THAT TRIGGER COURTESY TONE CHANGE
declare -g -a TRIGCT
TRIGCT[1]="Hurricane Force Wind Warning"
TRIGCT[2]="Severe Thunderstorm Warning"
TRIGCT[3]="Severe Thunderstorm Watch"
TRIGCT[4]="Tropical Storm Warning"
TRIGCT[5]="Coastal Flood Warning"
TRIGCT[6]="Winter Storm Warning"
TRIGCT[7]="Thunderstorm Warning"
TRIGCT[8]="Extreme Wind Warning"
TRIGCT[9]="Storm Surge Warning"
TRIGCT[10]="River Flood Warning"
TRIGCT[11]="Flash Flood Warning"
TRIGCT[12]="Ice Storm Warning"
TRIGCT[13]="Hurricane Warning"
TRIGCT[14]="Blizzard Warning"
TRIGCT[15]="Tornado Warning"
TRIGCT[16]="Hurricane Watch"
TRIGCT[17]="Tornado Watch"
TRIGCT[18]="Flood Warning"

# Initialize Message Strings
function init_warnings {

	declare -g -a WS
	declare -g -a WA

	# WARNING STRINGS

	WS[1]="Hurricane Force Wind Warning"
	WS[2]="Severe Thunderstorm Warning"
	WS[3]="Severe Thunderstorm Watch"
	WS[4]="Winter Weather Advisory"
	WS[5]="Tropical Storm Warning"
	WS[6]="Special Marine Warning"
	WS[7]="Freezing Rain Advisory"
	WS[8]="Special Weather Statement"
	WS[9]="Excessive Heat Warning"
	WS[10]="Coastal Flood Advisory"
	WS[11]="Coastal Flood Warning"
	WS[12]="Winter Storm Warning"
	WS[13]="Tropical Storm Watch"
	WS[14]="Thunderstorm Warning"
	WS[15]="Small Craft Advisory"
	WS[16]="Extreme Wind Warning"
	WS[17]="Excessive Heat Watch"
	WS[18]="Wind Chill Advisory"
	WS[19]="Storm Surge Warning"
	WS[20]="River Flood Warning"
	WS[21]="Flash Flood Warning"
	WS[22]="Coastal Flood Watch"
	WS[23]="Winter Storm Watch"
	WS[24]="Wind Chill Warning"
	WS[25]="Thunderstorm Watch"
	WS[26]="Fire Weather Watch"
	WS[27]="Dense Fog Advisory"
	WS[28]="Storm Surge Watch"
	WS[29]="River Flood Watch"
	WS[30]="Ice Storm Warning"
	WS[31]="Hurricane Warning"
	WS[32]="High Wind Warning"
	WS[33]="Flash Flood Watch"
	WS[34]="Red Flag Warning"
	WS[35]="Blizzard Warning"
	WS[36]="Tornado Warning"
	WS[37]="Hurricane Watch"
	WS[38]="High Wind Watch"
	WS[39]="Frost Advisory"
	WS[40]="Freeze Warning"
	WS[41]="Wind Advisory"
	WS[42]="Tornado Watch"
	WS[43]="Storm Warning"
	WS[44]="Heat Advisory"
	WS[45]="Flood Warning"
	WS[46]="Gale Warning"
	WS[47]="Freeze Watch"
	WS[48]="Flood Watch"

	# ANNOUNCEMENT STRINGS

	WA[1]="01"
	WA[2]="02"
	WA[3]="03"
	WA[4]="04"
	WA[5]="05"
	WA[6]="06"
	WA[7]="07"
	WA[8]="08"
	WA[9]="09"
	WA[10]="10"
	WA[11]="11"
	WA[12]="12"
	WA[13]="13"
	WA[14]="14"
	WA[15]="15"
	WA[16]="16"
	WA[17]="17"
	WA[18]="18"
	WA[19]="19"
	WA[20]="20"
	WA[21]="21"
	WA[22]="22"
	WA[23]="23"
	WA[24]="24"
	WA[25]="25"
	WA[26]="26"
	WA[27]="27"
	WA[28]="28"
	WA[29]="29"
	WA[30]="30"
	WA[31]="31"
	WA[32]="32"
	WA[33]="33"
	WA[34]="34"
	WA[35]="35"
	WA[36]="36"
	WA[37]="37"
	WA[38]="38"
	WA[39]="39"
	WA[40]="40"
	WA[41]="41"
	WA[42]="42"
	WA[43]="43"
	WA[44]="44"
	WA[45]="45"
	WA[46]="46"
	WA[47]="47"
	WA[48]="48"

}

function autoskymulti_log {
	echo "$(date) - $1" >>$AutoSkyMulti_log
}

AutoSkyMulti_init

# Check for test file set in AutoSkyMulti.ini
if [ -e "$TMPDIR/test.file" ]; then
	/bin/cp -f $TMPDIR/test.file $NFILE1
	/bin/rm -f $TMPDIR/test.file
else
	# No test file PULL THE REAL INFORMATION FROM NWS
	if [ -e $NFILE1 ]; then /bin/rm $NFILE1; fi
	for X in "${OF[@]}"; do
		/usr/bin/curl -s $X >>$NFILE1
		curlstat="$?"
		if [ $curlstat -ne 0 ]; then # Exit if curl couldn't pull data
			autoskymulti_log "Error getting data from NWS!"
			echo "Error getting data from NWS!"
			exit -95
		fi
	done
fi

# Remove wrong <title> sections
/bin/sed -i '/Current/d' $NFILE1
# COPY ONLY ONE SECTION TYPE (can be multiple)
/bin/sed -i '/title/p' $NFILE1
/bin/sed -i "1d" $NFILE1

# NOW GET RID OF THE MARKERS
/bin/sed -i 's%</title>%%' $NFILE1
/bin/sed -i 's%<title>%%' $NFILE1

# Remove extra whitespace
/bin/sed -i 's/^[ \t]*//' $NFILE1

# Remove duplicate lines
/usr/bin/awk '!seen[$0]++' $NFILE1 >$NFILE2

# Entirely remove certian alerts
# Uncomment ones to filter out
# REMOVE COLON TO ENABLE BLOCKING
if [ "$BLOCKING" = true ]; then
	:
	#/bin/sed -i '/Statement/d' $NFILE2
	#/bin/sed -i '/Advisory/d' $NFILE2
	#/bin/sed -i '/Watch/d' $NFILE2
	#/bin/sed -i '/Warning/d' $NFILE2
	#/bin/sed -i '/Hurricane Force Wind Warning/d' $NFILE2
	#/bin/sed -i '/Severe Thunderstorm Warning/d' $NFILE2
	#/bin/sed -i '/Severe Thunderstorm Watch/d' $NFILE2
	#/bin/sed -i '/Winter Weather Advisory/d' $NFILE2
	#/bin/sed -i '/Tropical Storm Warning/d' $NFILE2
	#/bin/sed -i '/Special Marine Warning/d' $NFILE2
	#/bin/sed -i '/Freezing Rain Advisory/d' $NFILE2
	#/bin/sed -i '/Special Weather Statement/d' $NFILE2
	#/bin/sed -i '/Excessive Heat Warning/d' $NFILE2
	#/bin/sed -i '/Coastal Flood Advisory/d' $NFILE2
	#/bin/sed -i '/Coastal Flood Warning/d' $NFILE2
	#/bin/sed -i '/Winter Storm Warning/d' $NFILE2
	#/bin/sed -i '/Tropical Storm Watch/d' $NFILE2
	#/bin/sed -i '/Thunderstorm Warning/d' $NFILE2
	#/bin/sed -i '/Small Craft Advisory/d' $NFILE2
	#/bin/sed -i '/Extreme Wind Warning/d' $NFILE2
	#/bin/sed -i '/Excessive Heat Watch/d' $NFILE2
	#/bin/sed -i '/Wind Chill Advisory/d' $NFILE2
	#/bin/sed -i '/Storm Surge Warning/d' $NFILE2
	#/bin/sed -i '/River Flood Warning/d' $NFILE2
	#/bin/sed -i '/Flash Flood Warning/d' $NFILE2
	#/bin/sed -i '/Coastal Flood Watch/d' $NFILE2
	#/bin/sed -i '/Winter Storm Watch/d' $NFILE2
	#/bin/sed -i '/Wind Chill Warning/d' $NFILE2
	#/bin/sed -i '/Thunderstorm Watch/d' $NFILE2
	#/bin/sed -i '/Fire Weather Watch/d' $NFILE2
	#/bin/sed -i '/Dense Fog Advisory/d' $NFILE2
	#/bin/sed -i '/Storm Surge Watch/d' $NFILE2
	#/bin/sed -i '/River Flood Watch/d' $NFILE2
	#/bin/sed -i '/Ice Storm Warning/d' $NFILE2
	#/bin/sed -i '/Hurricane Warning/d' $NFILE2
	#/bin/sed -i '/High Wind Warning/d' $NFILE2
	#/bin/sed -i '/Flash Flood Watch/d' $NFILE2
	#/bin/sed -i '/Red Flag Warning/d' $NFILE2
	#/bin/sed -i '/Blizzard Warning/d' $NFILE2
	#/bin/sed -i '/Tornado Warning/d' $NFILE2
	#/bin/sed -i '/Hurricane Watch/d' $NFILE2
	#/bin/sed -i '/High Wind Watch/d' $NFILE2
	#/bin/sed -i '/Frost Advisory/d' $NFILE2
	#/bin/sed -i '/Freeze Warning/d' $NFILE2
	#/bin/sed -i '/Wind Advisory/d' $NFILE2
	#/bin/sed -i '/Tornado Watch/d' $NFILE2
	#/bin/sed -i '/Storm Warning/d' $NFILE2
	#/bin/sed -i '/Heat Advisory/d' $NFILE2
	#/bin/sed -i '/Flood Warning/d' $NFILE2
	#/bin/sed -i '/Gale Warning/d' $NFILE2
	#/bin/sed -i '/Freeze Watch/d' $NFILE2
	#/bin/sed -i '/Flood Watch/d' $NFILE2
fi

# DOES NEW NWS FILE = OLD SAVE FILE
/usr/bin/diff -iabBEqw $NFILE2 $FILESAVE >/dev/null 2>/dev/null
# If match=0  non match=1 error=2
# This result is printed if running manually ignored otherwise
Xresult="$?"
echo "AutoSkyMulti Xresult is $Xresult"

case $Xresult in
0)
	# MATCH - NOTHING TO DO
	exit 0
	;;
1)
	# CURRENT VS LAST MISMATCH - CHANGE ANNOUNCEMENT
	# IF RESULT HAS NO LINES - PROCESS ERROR BELOW
	Xresult=$(wc -l <$NFILE2)

	case $Xresult in
	0)
		# FAILURE MODE 0 - FILE SHOULD HAVE AT LEAST ONE REMAINING LINE
		exit -5
		;;
	*)
		# MIGHT BE A CLEAR MESSAGE OR SINGLE or MULTIPLE ALERT
		# CHECK FOR ALL CLEAR MESSAGE if NOT SET ANNOUNCEMENTS
		/bin/grep -i "issued" $NFILE2 >/dev/null
		Yresult=$?

		if [ $Yresult -eq 1 ]; then
			#  MATCHED - NO W, W or As
			# COMMIT TO CHANGE
			# COPY CURRENT MESSAGE TO SAVE MESSAGE FILE
			# THIS BECOMES THE "Existing" Weather Conditions
			/bin/cp -f $NFILE2 $FILESAVE
			# SAY NWS HAS CLEARED ALL ALERTS, WATCHES and WARNINGS
			if [ "$SAYALLCLEAR" = true ]; then
				if [ "$PUSHOVER" = true ]; then
					curl -s \
						--form-string "token=$POTOKEN" \
						--form-string "user=$POUSER" \
						--form-string "message=WX Alerts Cleared" \
						https://api.pushover.net/1/messages.json >/dev/null
				fi
				for Ni in $NODE; do
					if [ ! -z "$Ni" ]; then /usr/sbin/asterisk -rx "rpt localplay $Ni $WXA/$A1FILE"; fi
				done
			fi
			# Clear Warnigs text file
			>$TMPDIR/warnings.txt

			# COPY WORD-SPACE AUDIO to the WX TAIL MESSAGE
			# THE WORD-SPACE WAV IS ASN99
			/bin/rm -f $WXT/$TAILMSG
			/bin/cp -f $WXA/asn99.wav $WXT/$TAILMSG
			autoskymulti_log "Alerts Cleared"
			if [ "$AUTOCT" = true ]; then
				/bin/cp -f $WXA/$LOCALCT $CTDIR/$ASTLOCALCT
				/bin/cp -f $WXA/$LINKCT $CTDIR/$ASTLINKCT
			fi
			/bin/sync
			exit 0
			# exit $?
		else
			# NO MATCH - WE HAVE A CHANGE IN THE WEATHER
			init_warnings

			# COMMITTED TO CHANGE
			# COPY CURRENT MESSAGE TO SAVE MESSAGE FILE

			/bin/cp -f $NFILE2 $FILESAVE

			# ONLY PROCESS LINES WITH SPECIFIC KEY WORDS
			#   ALL WARNINGS BEFORE WATCHES BEFORE ...

			rm -f $NFILE3
			/bin/grep -i "Warning" <$NFILE2 >$NFILE3
			/bin/grep -i "Watch" <$NFILE2 >>$NFILE3
			/bin/grep -i "Advisory" <$NFILE2 >>$NFILE3
			/bin/grep -i "Special Weather" <$NFILE2 >>$NFILE3

			# CLEAR THE EXISTING TAILMSG
			# COPY WORD-SPACE AUDIO to the WX TAIL MESSAGE
			# THE WORD-SPACE WAV IS ASN99
			/bin/cp -f $WXA/asn99.wav $WXT/$TAILMSG

			# MARK AS NOTHING FOUND IN FILE NFILE3
			FOUNDONE=0
			# Clear Warnings text file
			>$TMPDIR/warnings.txt
			First_Warning=1
			while IFS= read -r line; do

				# Look for string in current line
				# If match, copy audio and "pause" to wx-tail, continue (get next line)

				for ((i = 1; i < 49; i++)); do

					if [[ $line =~ ${WS[${i}]} ]]; then
						ANNN=${WA[$i]}

						# ANNN PARAMETER VALUE IS $ANNN
						if [ $ANNN = "000" ]; then
							# Announcement ALREADY used once! -- don't add it again
							break
						else
							# Announcement added. Mark WA array as announcement used
							WA[$i]="000"
							# Put alert in warnings.txt file
							if [ $First_Warning -eq 1 ]; then
								echo "$Coverage_Area - " >$TMPDIR/warnings.txt
								First_Warning=0
							fi
							echo "[ ${WS[${i}]} ]" >>$TMPDIR/warnings.txt

						fi
						# BUILD TAILMSG - NOW ADD A "AUDIO TIC" TO THE TAILMSG
						/bin/rm -f $TMPDIR/$TFILEW #Make available for output

						$CATWAV $WXT/$TAILMSG $WXA/asn95C.wav $TMPDIR/$TFILEW
						/bin/cp -f $TMPDIR/$TFILEW $WXT/$TAILMSG

						# BUILD TAILMSG - NOW ADDING THE NEW ALERT TO THE TAILMSG
						/bin/rm -f $TMPDIR/$TFILEW #Make available for output
						$CATWAV $WXT/$TAILMSG $WXA/${BUILD1}${ANNN}${BUILD3} $TMPDIR/$TFILEW
						/bin/cp -f $TMPDIR/$TFILEW $WXT/$TAILMSG

						# BUILD TAILMSG - NOW ADD A "WORDSPACE" TO THE TAILMSG
						/bin/rm -f $TMPDIR/$TFILEW #Make available for output
						$CATWAV $WXT/$TAILMSG $WXA/asn99.wav $TMPDIR/$TFILEW
						/bin/cp -f $TMPDIR/$TFILEW $WXT/$TAILMSG

						FOUNDONE=1
						autoskymulti_log "Alert issued - $line"
						/bin/sync
						if [ "$PUSHOVER" = true ]; then
							autoskymulti_log "Sending Pushover Message"
							curl -s \
								--form-string "token=$POTOKEN" \
								--form-string "user=$POUSER" \
								--form-string "message=Alert Issued - $line" \
								https://api.pushover.net/1/messages.json >/dev/null
						fi
						break
					else
						# CURRENT TEST DOES NOT MATCH - SHOULD IT BE ADDED TO LIST?
						# echo WS STRING NO MATCH
						:
					fi
				done

			done <"$NFILE3"

			/bin/sync

			if [[ $FOUNDONE -eq 0 ]]; then
				# DIDN'T FIND A MATCH - PLAY ERROR TONE
				for Ni in $NODE; do
					if [ ! -z "$Ni" ]; then /usr/sbin/asterisk -rx "rpt localplay $Ni $WXA/$A3FILE"; fi
				done
			else
				# Copy 1 second of tail to message
				/bin/cp -f $WXT/$TAILMSG $TMPDIR/$TFILEW
				$CATWAV $TMPDIR/$TFILEW $WXA/silence1.wav $WXT/$TAILMSG

				if [ "$SAYALERT" = true ]; then
					# NOW SAY SOMETHING ABOUT THE NEW LEVEL OF WARNINGS
					# THIS WILL BE A LOCAL PLAY OF A2FILE
					for Ni in $NODE; do
						if [ ! -z "$Ni" ]; then /usr/sbin/asterisk -rx "rpt localplay $Ni $WXA/$A2FILE"; fi
					done
					/bin/sleep 3
					# NOW PLAY THE NEW WX STATUS
					MSG=$(basename $TAILMSG .wav)
					for Ni in $NODE; do
						if [ ! -z "$Ni" ]; then /usr/sbin/asterisk -rx "rpt localplay $Ni $WXT/$MSG"; fi
					done
				fi
				# Change to ALERT ACTIVE courtesy tone if ALERTS file contains a trigger
				if [ "$AUTOCT" = true ]; then
					for WX in "${TRIGCT[@]}"; do
						if /bin/grep -i "$WX" $NFILE2; then
							autoskymulti_log "Changing to ALERT CT"
							/bin/cp -f $WXA/$WXCT $CTDIR/$ASTLOCALCT
							/bin/cp -f $WXA/$WXCT $CTDIR/$ASTLINKCT
							/bin/sync
							break
						fi
					done
				fi
			fi
			exit 0
		fi
		;;
	esac
	exit $?
	;;
2)
	#DIFF COMMAND FAILED. Xresult was 2.
	#Probably no first time saved file so initialize it
	/bin/cp -f $NFILE1 $FILESAVE

	exit -92
	;;
*)
	#BIG FAIL. Xresult was NOT 0, 1 or 2.
	exit -93
	;;
esac
exit -94
